### ISSUE TITLE
Seems to somehow...store progress when nothing is smelting?

### ISSUE THREAD

**Issue by Traehgniw** [InZan123/Unloaded-Activity-Fabric#3]
1.19.2 Fabric

I left a furnace and a smoker with fuel in the slot but nothing cooking, did some mining with the furnace and smoker unloaded, then came back and put some ore in the furnace and a piece of steak in the smoker and both the steak and the first two ores cooked instantly.

**Comment by InZan123** [comment]
Are you playing with some other mods installed? I did some testing and found that using Lithium I also get this bug. 

What I'm guessing it's doing is not ticking furnaces when it isn't needed. That's a problem because my mod uses that ticking to keep track of the last time it was loaded which is then used to calculate in what state the furnace should be in.

A temporary fix you could do is to is to go to your config folder in your minecraft folder and edit "lithium.properties" to include this at the end of the file:
```properties
mixin.world.block_entity_ticking.sleeping=false
```
This will basically just disable the optimization which doesn't work with my mod.

Another less complicated fix you can do is to disable updating furnaces in my mod.

I will see if I can try to fix this in a future update.

**Comment by InZan123** [comment]
This bug has been fixed in the 0.4.0 release. You can undo the workaround once you've updated.
