### ISSUE TITLE
Crash when entering Eden Ring portal

### ISSUE THREAD

**Issue by DennHenda** [InZan123/Unloaded-Activity-Fabric#4]
I added Unloaded Activity later on, after I had already been exploring the Eden Ring dimension.  A new player joined the server and entered the portal for the first time and the server crashed.  I have not tried to enter the portal since removing Unloaded Activity, but I can test it after awhile if needed.

May possibly be BetterX or BCLib?

Let me know if I can give you any more helpful information!

Here's the server crash log:
https://mclo.gs/RyFETB9

**Comment by InZan123** [comment]
It seems like my mod tried to grow a modded tree. Vanilla saplings only have 2 states before turning into a tree and what I think happened was that my mod wanted to advance the tree 2 steps but then on the second step it had already became a tree making the game crash. Maybe its because the modded sapling only had 1 state and my mod didn't know that but I'm not sure.

For the time being you could try disabling the "Grow Saplings" option. Find "unloaded-activity.json" in the config folder inside the server folder. Then you just set "growSaplings" to false.

**Comment by InZan123** [comment]
I've released v0.4.0 now but I'm not sure if this is fixed because I had a hard time getting this crash and only got it a few times. Can you try the latest version and confirm if it actually is fixed?

**Comment by DennHenda** [comment]
Hey, sorry for the late reply. I just recently updated my server, reverted the sapling setting in the config and all that. I haven't been able to cause a crash again so I think you got it.

Thanks for the fix and the awesome mod!
