### ISSUE TITLE
[Enhauncement] Config to disable vines and glowberries

### ISSUE THREAD

**Issue by dlfnn** [InZan123/Unloaded-Activity-Fabric#6]
Because the nature of world generation, vines and glowberries each generates massively in jungles and lush caves, and because they grow due to random tick, large lag spikes can occure while traveling back and forth between those biomes. 

![ECMHS~7 H_RDN5PHPB `DQF](https://user-images.githubusercontent.com/94152497/236105339-5ddcd958-6e46-4ff4-a7b2-9801e2a2a8b2.jpg)

![image](https://user-images.githubusercontent.com/94152497/236105453-a78e9fc9-5f5e-45eb-8a0e-e858e5c4b69e.png)

Because that most players don't have a really high demand on farming glowberries and vines, it would be nice if they could be toggled off.

**Comment by InZan123** [comment]
The latest version of this mod currently doesn't grow vines and glowberries. If you are unable to disable something in my mod then that probably means it isn't supported.

Do the lagspikes happen consistently and do they happen anywhere else in the world? _(Do note that for new chunks you need to load them in twice since my mod skips simulating newly generated chunks)_ 
The lagspikes might just be my mod being inefficient in general so it shouldn't only happen in lush caves and jungles. If it does happen consistently and only in those areas, maybe you could send a download to the world since I'm unable to reproduce the lagspikes.
Simulation distance could also affect the performance of the mod and I usually have mine set to 5.

Though I've made some optimizations for the next update which should reduce lag a bit, so that might solve the issue you're having.

**Comment by dlfnn** [comment]
Oh you are correct. This does happens when there are no vines nor glowberries. Nevermind, good luck with the optimization then!
